# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180505_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['category']},
        ),
    ]
