# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20180505_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='height',
        ),
        migrations.RemoveField(
            model_name='images',
            name='width',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
